name: tennis-ml
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - idna==3.4
      - ipywidgets==8.1.7
      - jinja2==3.1.4
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - multidict==6.5.1
      - narwhals==1.44.0
      - nbformat==5.10.4
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-nccl-cu12==2.27.3
      - pandas==2.3.0
      - pillow==11.0.0
      - plotly==6.1.2
      - propcache==0.3.2
      - pyparsing==3.2.3
      - pytz==2025.2
      - referencing==0.36.2
      - requests==2.28.1
      - rpds-py==0.25.1
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - sympy==1.13.3
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - torch==2.1.2+cu118
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt21cu118
      - torch-sparse==0.6.18+pt21cu118
      - torchaudio==2.1.2+cu118
      - torchvision==0.16.2+cu118
      - tqdm==4.67.1
      - triton==2.1.0
      - tzdata==2025.2
      - urllib3==1.26.13
      - widgetsnbextension==4.0.14
      - xgboost==3.0.2
      - yarl==1.20.1
